from __future__ import annotations

from datetime import datetime
from uuid import UUID, uuid4

from sqlalchemy import JSON, DateTime, ForeignKey, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class Alert(Base):
    """Suspicious event generated by rule and anomaly engines."""

    __tablename__ = "alerts"

    id: Mapped[UUID] = mapped_column(Uuid, primary_key=True, default=uuid4)
    transaction_id: Mapped[UUID] = mapped_column(Uuid, ForeignKey("transactions.id"), index=True)

    severity: Mapped[str] = mapped_column(String(32), default="medium", index=True)
    alert_type: Mapped[str] = mapped_column(String(64), index=True)
    status: Mapped[str] = mapped_column(String(32), default="new")
    score: Mapped[float] = mapped_column(default=0)
    reason: Mapped[str] = mapped_column(Text)
    explanation_json: Mapped[dict] = mapped_column(JSON, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=False), default=datetime.utcnow)

    transaction: Mapped[Transaction] = relationship(back_populates="alerts")


from app.models.transaction import Transaction  # noqa: E402
